debug: true

server:
  contextPath: /uaa
  port: 8080

management:
  context_path: /admin
security:
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**, /info
  user:
    password: password

ribbon:
  eureka:
    enabled: true

spring:
  jpa:
    hibernate.ddl-auto: create-drop
  thymeleaf:
    cache: false
eureka:
  instance:
      preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

